baseurl = "/"
languageCode = "en-us"
theme = ["hugo-loremipsum"]
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # "light" or "dark"
  themeColor = "pink"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2
  # show selector to switch language
  showLanguageSelector = false
  # set theme to full screen width
  fullWidthTheme = false
  # center theme with default width
  centerTheme = true
  # set a custom favicon (default is a `themeColor` square)
  favicon = "img/favicon.ico"

[languages]
  [languages.en]
   languageName = "English" 
   title = "【vltraheaven】"
    subtitle = "DevOps // GameDev // Emulation"
    keywords = ["devops", "game development", "linux", "emulation", "MAME", "docker", "kubernetes", "secdevops"]
    copyright = "【vltraheaven】 © 2019"
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
    logoText = "$ ./vltraheaven.io"
    logoHomeLink = "/"
    # or
    #
    # path = "/img/title.gif"
    #alt = "VltraHeaven"

    [languages.en.menu]
    #  [[languages.en.menu.main]]
    #    identifier = "about"
    #    name = "About"
    #    url = "/about"
    #  [[languages.en.menu.main]]
    #    identifier = "showcase"
    #    name = "Showcase"
    #    url = "/showcase"
