baseURL = 'https://vltraheaven.io/'
languageCode = 'en-us'
title = 'vltraheaven.io'

theme = ['pico']

[module]
[[module.imports]]
  path = 'github.com/negrel/hugo-theme-pico'

[markup.goldmark.renderer]
  unsafe = true

[params]
description = 'vltraheaven'
email = "contact@vltraheaven.io"
#darkMode = 'always'

# Navigation bar
[menu]

[[menu.main]]
identifier = "home" # identifier is use for translations
pre = "" # pre is inserted before the translation (icons, image, etc)
url = "/" 
weight = 10

[[menu.main]]
identifier = "blog" # identifier is use for translations
pre = "" # pre is inserted before the translation (icons, image, etc)
url = "/blog/" 
weight = 20 

[[menu.main]]
identifier = "contact" # identifier is use for translations
pre = "" # pre is inserted before the translation (icons, image, etc)
url = "/#contact" 
weight = 30 

# Syntax highlightning
[markup.highlight]
guessSyntax = true 
lineNumbersInTable = true 
noClasses = false # Set to false to use the Pico default theme.
tabWidth = 2 

[taxonomies]
category = "categories"
tag = "tags"

[languages.en]
title = "vltraheaven.io"
keywords = ["devops", "linux", "kubernetes"]
copyright = "【vltraheaven】 © 2023"
contentDir = 'content/en'
languageCode = 'en'
languageName = 'English'
weight = 0
